// Grid Sentinel — shared mock data for the entire app.
export type StateData = {
  id: string;
  name: string;
  // Approx % coords on a 1000x1000 viewBox roughly resembling India
  x: number;
  y: number;
  demand: number; // GW
  forecast: number;
  renewable: number; // GW
  battery: number; // %
  risk: number; // 0-100
  blackout: number; // 0-100 probability %
  recommendation: string;
};

export const STATES: StateData[] = [
  {
    id: "JK",
    name: "Jammu & Kashmir",
    x: 360,
    y: 110,
    demand: 2.4,
    forecast: 2.7,
    renewable: 0.8,
    battery: 62,
    risk: 28,
    blackout: 4,
    recommendation: "Hold reserves, stable inflows",
  },
  {
    id: "PB",
    name: "Punjab",
    x: 360,
    y: 200,
    demand: 9.1,
    forecast: 10.6,
    renewable: 2.1,
    battery: 48,
    risk: 46,
    blackout: 9,
    recommendation: "Pre-dispatch gas peakers",
  },
  {
    id: "DL",
    name: "Delhi",
    x: 410,
    y: 240,
    demand: 7.8,
    forecast: 9.4,
    renewable: 0.9,
    battery: 38,
    risk: 78,
    blackout: 21,
    recommendation: "Activate demand-response tier 2",
  },
  {
    id: "RJ",
    name: "Rajasthan",
    x: 320,
    y: 300,
    demand: 14.2,
    forecast: 15.0,
    renewable: 11.4,
    battery: 71,
    risk: 36,
    blackout: 6,
    recommendation: "Curtail solar at 14:00 IST",
  },
  {
    id: "UP",
    name: "Uttar Pradesh",
    x: 470,
    y: 270,
    demand: 22.6,
    forecast: 25.8,
    renewable: 3.8,
    battery: 41,
    risk: 64,
    blackout: 14,
    recommendation: "Import 1.2 GW from NR pool",
  },
  {
    id: "GJ",
    name: "Gujarat",
    x: 280,
    y: 380,
    demand: 18.4,
    forecast: 19.1,
    renewable: 13.2,
    battery: 66,
    risk: 32,
    blackout: 5,
    recommendation: "Wind ramp-up forecast 18:30",
  },
  {
    id: "MH",
    name: "Maharashtra",
    x: 360,
    y: 460,
    demand: 26.1,
    forecast: 28.9,
    renewable: 8.4,
    battery: 52,
    risk: 81,
    blackout: 24,
    recommendation: "Crisis protocol: shed 600 MW industrial",
  },
  {
    id: "MP",
    name: "Madhya Pradesh",
    x: 430,
    y: 380,
    demand: 12.8,
    forecast: 13.4,
    renewable: 4.6,
    battery: 58,
    risk: 38,
    blackout: 7,
    recommendation: "Stable — battery dispatch at peak",
  },
  {
    id: "CG",
    name: "Chhattisgarh",
    x: 510,
    y: 410,
    demand: 6.2,
    forecast: 6.5,
    renewable: 1.1,
    battery: 64,
    risk: 22,
    blackout: 3,
    recommendation: "Surplus available for export",
  },
  {
    id: "OD",
    name: "Odisha",
    x: 560,
    y: 440,
    demand: 7.4,
    forecast: 7.9,
    renewable: 1.8,
    battery: 60,
    risk: 30,
    blackout: 5,
    recommendation: "Coastal wind nominal",
  },
  {
    id: "WB",
    name: "West Bengal",
    x: 610,
    y: 350,
    demand: 11.6,
    forecast: 12.8,
    renewable: 1.4,
    battery: 44,
    risk: 58,
    blackout: 12,
    recommendation: "Monitor Kolkata feeder load",
  },
  {
    id: "BR",
    name: "Bihar",
    x: 540,
    y: 290,
    demand: 8.1,
    forecast: 9.0,
    renewable: 1.2,
    battery: 39,
    risk: 54,
    blackout: 11,
    recommendation: "Schedule 400 MW import",
  },
  {
    id: "JH",
    name: "Jharkhand",
    x: 550,
    y: 340,
    demand: 5.4,
    forecast: 5.7,
    renewable: 0.7,
    battery: 56,
    risk: 26,
    blackout: 4,
    recommendation: "Coal baseload nominal",
  },
  {
    id: "TS",
    name: "Telangana",
    x: 420,
    y: 540,
    demand: 11.2,
    forecast: 12.3,
    renewable: 4.1,
    battery: 55,
    risk: 48,
    blackout: 9,
    recommendation: "Solar surplus 13:00–15:30",
  },
  {
    id: "AP",
    name: "Andhra Pradesh",
    x: 460,
    y: 600,
    demand: 12.0,
    forecast: 12.9,
    renewable: 5.6,
    battery: 61,
    risk: 42,
    blackout: 8,
    recommendation: "Pumped storage charging window",
  },
  {
    id: "KA",
    name: "Karnataka",
    x: 380,
    y: 620,
    demand: 14.8,
    forecast: 15.6,
    renewable: 8.9,
    battery: 68,
    risk: 34,
    blackout: 5,
    recommendation: "Wind-solar hybrid optimal",
  },
  {
    id: "KL",
    name: "Kerala",
    x: 380,
    y: 720,
    demand: 4.6,
    forecast: 4.9,
    renewable: 1.9,
    battery: 72,
    risk: 24,
    blackout: 3,
    recommendation: "Hydro reserves healthy",
  },
  {
    id: "TN",
    name: "Tamil Nadu",
    x: 430,
    y: 720,
    demand: 17.4,
    forecast: 18.6,
    renewable: 10.2,
    battery: 64,
    risk: 40,
    blackout: 7,
    recommendation: "Wind output peaking SW monsoon",
  },
  {
    id: "AS",
    name: "Assam",
    x: 720,
    y: 270,
    demand: 3.1,
    forecast: 3.3,
    renewable: 0.5,
    battery: 50,
    risk: 32,
    blackout: 5,
    recommendation: "Gas dispatch nominal",
  },
  {
    id: "HR",
    name: "Haryana",
    x: 390,
    y: 230,
    demand: 8.4,
    forecast: 9.6,
    renewable: 2.0,
    battery: 47,
    risk: 55,
    blackout: 11,
    recommendation: "DR enrollment expand",
  },
];

export type Alert = {
  id: string;
  level: "critical" | "warning" | "info" | "ok";
  state: string;
  title: string;
  detail: string;
  time: string;
};

export const SEED_ALERTS: Alert[] = [
  {
    id: "a1",
    level: "critical",
    state: "Maharashtra",
    title: "Demand surge detected",
    detail: "Mumbai cluster +2.8 GW above forecast band",
    time: "14:02:11",
  },
  {
    id: "a2",
    level: "warning",
    state: "Gujarat",
    title: "Wind generation declining",
    detail: "Kutch corridor −1.4 GW over 20 min",
    time: "14:01:48",
  },
  {
    id: "a3",
    level: "critical",
    state: "Delhi",
    title: "Grid stress increasing",
    detail: "Frequency 49.78 Hz — DR tier 2 armed",
    time: "14:00:33",
  },
  {
    id: "a4",
    level: "warning",
    state: "Rajasthan",
    title: "Solar output reduction",
    detail: "Cloud cover band advancing SW→NE",
    time: "13:58:09",
  },
  {
    id: "a5",
    level: "info",
    state: "Karnataka",
    title: "Battery dispatch optimal",
    detail: "Pavagada cluster discharging 420 MW",
    time: "13:55:21",
  },
  {
    id: "a6",
    level: "ok",
    state: "Tamil Nadu",
    title: "Wind ramp confirmed",
    detail: "Muppandal +680 MW over baseline",
    time: "13:52:02",
  },
];

export const FORECAST_HORIZONS = ["Now", "+6h", "+12h", "+24h", "+48h"] as const;

export const ENERGY_MIX = {
  solar: 32,
  wind: 24,
  battery: 14,
  gas: 18,
  coal: 12,
};
