import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState, type ReactNode } from "react";
import { BatteryCharging, CloudSnow, Fuel, Wind, ShieldCheck } from "lucide-react";

export const Route=createFileRoute("/digital-twin")({head:()=>({meta:[{title:"Polar Station Digital Twin · Grid Sentinel AI"},{name:"description",content:"Weather-aware digital twin for AI-driven energy management at polar research stations."}]}),component:DigitalTwin});

type Scenario={name:string;storm:number;light:number;wind:number;load:number};
const SCENARIOS:Scenario[]=[{name:"Nominal Weather",storm:10,light:15,wind:10,load:5},{name:"Polar Storm",storm:80,light:45,wind:55,load:18},{name:"Low-Light Event",storm:35,light:90,wind:20,load:12},{name:"Wind Derating",storm:25,light:25,wind:75,load:10}];

function DigitalTwin(){
 const [scenario,setScenario]=useState(0); const s=SCENARIOS[scenario];
 const r=useMemo(()=>{const solar=Math.max(0,34*(1-s.light/100)*(1-s.storm*.003));const wind=Math.max(0,28*(1-s.wind/100)*(1-s.storm*.002));const load=52*(1+s.load/100+s.storm*.0025);const battery=Math.max(0,18*(scenario===1?0.72:0.9));const generator=27;const renewable=solar+wind;const gap=Math.max(0,load-renewable-generator);let seed=0;let shortage=0;let minSoc=100;let fuel=0;for(let i=0;i<5000;i++){seed=(seed*1664525+1013904223+i+scenario*97)>>>0;const u=seed/4294967296;const stochasticGap=Math.max(0,gap*(0.75+u*0.5));const reserve=battery*(0.7+u*0.3)+generator*(0.85+u*0.15);if(stochasticGap>reserve*.45)shortage++;minSoc=Math.min(minSoc,Math.max(5,82-stochasticGap*.9));fuel+=Math.min(1,stochasticGap/35)}const shortageProbability=shortage/50;const fuelIndex=Math.min(100,20+fuel/50*100);const eue=Math.max(0,gap*(shortageProbability/100)*4);const action=shortageProbability>35?"Start backup generation; preserve battery for critical loads; defer non-critical demand.":shortageProbability>15?"Pre-dispatch battery and generator; shift deferrable lab loads.":s.light>70?"Protect SOC through the low-light window and minimize diesel cycling.":"Maintain reserve and monitor weather.";return {solar,wind,load,renewable,shortageProbability,minSoc,fuelIndex,eue,action};},[s,scenario]);
 return <div className="px-6 py-6 space-y-6"><section className="panel p-6"><div className="hud-label mb-2">POLAR STATION · DIGITAL TWIN · 5,000 SCENARIOS</div><h1 className="text-3xl font-display font-semibold">Weather-aware <span className="text-[oklch(0.72_0.18_245)]">energy intelligence</span>.</h1><p className="text-muted-foreground mt-2 max-w-3xl">A proof-of-concept microgrid twin for an isolated polar research station. It couples weather stress, load, renewable availability, battery reserve and backup generation into probabilistic risk and dispatch guidance.</p></section><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{SCENARIOS.map((x,i)=><button key={x.name} onClick={()=>setScenario(i)} className={`panel p-4 text-left ${scenario===i?"border-[oklch(0.72_0.18_245/0.6)]":""}`}><div className="hud-label">SCENARIO {String(i+1).padStart(2,"0")}</div><div className="font-display mt-1">{x.name}</div></button>)}</div><div className="grid grid-cols-1 xl:grid-cols-[1fr_380px] gap-6"><section className="panel p-6"><div className="hud-label mb-4">Station state · {s.name}</div><div className="grid md:grid-cols-2 gap-4"><Metric icon={<CloudSnow/>} label="Station load" value={`${r.load.toFixed(1)} kW`}/><Metric icon={<Wind/>} label="Renewable generation" value={`${r.renewable.toFixed(1)} kW`}/><Metric icon={<BatteryCharging/>} label="Minimum battery SOC" value={`${r.minSoc.toFixed(1)} %`}/><Metric icon={<Fuel/>} label="Fuel-use index" value={`${r.fuelIndex.toFixed(0)}`}/></div><div className="mt-6 grid md:grid-cols-3 gap-3"><Stat label="Shortage probability" value={`${r.shortageProbability.toFixed(1)} %`} warn={r.shortageProbability>15}/><Stat label="Expected unserved energy" value={`${r.eue.toFixed(2)} kWh`}/><Stat label="Renewable share" value={`${(r.renewable/r.load*100).toFixed(1)} %`}/></div></section><aside className="panel p-6"><div className="hud-label mb-2 flex items-center gap-2"><ShieldCheck size={13}/> SENTINEL DISPATCH</div><div className="font-display text-xl">{r.action}</div><div className="mt-5 space-y-2 text-xs font-mono"><Row k="Weather stress" v={`${s.storm}%`}/><Row k="Low-light penalty" v={`${s.light}%`}/><Row k="Wind derating" v={`${s.wind}%`}/><Row k="Scenario engine" v="5,000 stochastic paths"/><Row k="Operating mode" v="ADVISORY"/></div><div className="mt-5 text-[10px] text-muted-foreground">Synthetic proof-of-concept inputs; not live polar-station telemetry.</div></aside></div></div>;
}
function Metric({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="p-4 rounded-lg border border-[oklch(0.72_0.18_245/0.12)]"><div className="hud-label flex items-center gap-2">{icon}{label}</div><div className="font-mono text-xl mt-2">{value}</div></div>}
function Stat({label,value,warn}:{label:string;value:string;warn?:boolean}){return <div className="p-4 rounded-lg bg-[oklch(0.16_0.028_260/0.6)]"><div className="text-[10px] text-muted-foreground">{label}</div><div className={`font-mono text-lg mt-1 ${warn?"text-[oklch(0.82_0.17_75)]":""}`}>{value}</div></div>}
function Row({k,v}:{k:string;v:string}){return <div className="flex justify-between border-b border-[oklch(0.72_0.18_245/0.08)] pb-1"><span className="text-muted-foreground">{k}</span><span>{v}</span></div>}
