import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BatteryCharging, BrainCircuit, CloudSnow, Fuel, ShieldCheck, Wind } from "lucide-react";
import type { ReactNode } from "react";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Grid Sentinel AI · SIH26061 Polar Energy Management"},{name:"description",content:"AI-driven smart energy management decision support for polar research stations: load forecasting, renewable integration and fuel optimization under extreme conditions."}]}),component:Home});
const MODULES=[["01","Forecast","Load + renewable availability under weather uncertainty",CloudSnow,"/digital-twin"],["02","Simulate","5,000 stochastic station-energy scenarios",ShieldCheck,"/digital-twin"],["03","Optimize","Battery + backup dispatch with fuel awareness",BatteryCharging,"/simulation"],["04","Explain","Operator-facing AI recommendations and rationale",BrainCircuit,"/control-room"]] as const;
function Home(){return <div className="min-h-screen"><section className="px-6 md:px-12 py-20 max-w-[1500px] mx-auto"><div className="hud-label mb-5 flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-[oklch(0.85_0.21_145)] animate-pulse"/> SIH26061 · POLAR RESEARCH STATION · DECISION SUPPORT</div><div className="grid lg:grid-cols-[1.3fr_.7fr] gap-12 items-end"><div><h1 className="text-5xl md:text-7xl font-display font-semibold leading-[.95]">GRID SENTINEL <span className="text-[oklch(0.72_0.18_245)]">AI</span></h1><p className="mt-8 text-2xl md:text-3xl font-display max-w-4xl">Weather-aware energy intelligence for isolated polar stations.</p><p className="mt-5 text-muted-foreground max-w-2xl leading-relaxed">Forecast station demand and renewable availability, propagate uncertainty through thousands of scenarios, quantify energy-security risk, and recommend reserve-aware dispatch across renewables, battery and backup generation.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/digital-twin" className="px-5 py-3 rounded-lg bg-[oklch(0.72_0.18_245)] text-[oklch(0.1_0.02_260)] font-medium flex items-center gap-2">Open Polar Digital Twin <ArrowRight size={15}/></Link><Link to="/simulation" className="px-5 py-3 rounded-lg border border-[oklch(0.72_0.18_245/0.3)] flex items-center gap-2">Run Crisis Lab</Link></div></div><div className="panel p-6"><div className="hud-label mb-4">Problem → intelligence loop</div><div className="space-y-4 font-mono text-sm"><Row n="01" t="Weather + station state"/><Row n="02" t="Load / renewable forecast"/><Row n="03" t="Monte Carlo uncertainty"/><Row n="04" t="Risk + EUE + SOC"/><Row n="05" t="Constrained dispatch"/><Row n="06" t="Explainable recommendation"/></div></div></div></section><section className="px-6 md:px-12 pb-16 max-w-[1500px] mx-auto"><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{MODULES.map(([n,title,desc,Icon,to])=><Link key={title} to={to} className="panel p-5 hover:border-[oklch(0.72_0.18_245/0.5)] transition-colors"><div className="flex justify-between"><span className="hud-label">{n}</span><Icon size={17} className="text-[oklch(0.85_0.21_145)]"/></div><div className="font-display text-xl mt-5">{title}</div><div className="text-sm text-muted-foreground mt-2">{desc}</div></Link>)}</div></section><section className="px-6 md:px-12 pb-20 max-w-[1500px] mx-auto"><div className="panel p-6"><div className="grid md:grid-cols-3 gap-6"><Stat icon={<Wind/>} label="Renewable integration" text="Wind + solar availability are stress-tested against weather conditions."/><Stat icon={<Fuel/>} label="Fuel optimization" text="Backup generation is treated as a constrained reserve, not the default source."/><Stat icon={<ShieldCheck/>} label="Operational boundary" text="Prototype decision support; synthetic inputs are explicitly separated from live telemetry."/></div></div></section></div>}
function Row({n,t}:{n:string;t:string}){return <div className="flex items-center gap-3 border-b border-[oklch(0.72_0.18_245/0.1)] pb-3"><span className="text-[oklch(0.72_0.18_245)]">{n}</span><span>{t}</span></div>}
function Stat({icon,label,text}:{icon:ReactNode;label:string;text:string}){return <div><div className="flex items-center gap-2 font-display">{icon}{label}</div><p className="text-sm text-muted-foreground mt-2">{text}</p></div>}
